### ISSUE TITLE
Suggest: add license, tests and/or continuous integration

### ISSUE THREAD

**Issue by richelbilderbeek** [Sabor117/PathWAS#1]
Hi @Sabor117, 

You just gave an awesome presentation at EMGM, so I checked out this repo, to decide if I will use PathWAS. Things I personally value are an open license, tests and continuous integration, which are all three missing. I understand: not every supervisor allows the time for that, catalyzed with the pressure of getting things published. 

I suggest to add these, and I do volunteer to do this myself and/or together. I would also be open to an online meeting first!

Cheers, Richel Bilderbeek, postdoc

**Comment by Sabor117** [comment]
Hi @richelbilderbeek,

Thank you for the feedback with regards to this! I have to admit this is still early days for the package and it isn't really yet even in a functional state! I am sure that we will be considering all three of these aspects down the line, but first (of course) actually have to get this into a working state.

This is definitely something I will have to consider at some point though, so thank you for offering your assistance as well. However, for the time being it's something we'll just have to be aware of and then come back to down the line.
